"""Make next_player nullable

Revision ID: a8db9f9f66ec
Revises: 2d2b96a1e492
Create Date: 2025-06-26 13:09:50.491687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8db9f9f66ec'
down_revision: Union[str, Sequence[str], None] = '2d2b96a1e492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matches', 'next_player',
               existing_type=postgresql.ENUM('X', 'O', name='player'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matches', 'next_player',
               existing_type=postgresql.ENUM('X', 'O', name='player'),
               nullable=False)
    # ### end Alembic commands ###
